CONFIG_ZMK_KEYBOARD_NAME="Kiwi-36"

# Optimize for Nice!View
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
CONFIG_LV_USE_THEME_MONO=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y

# POWER MANAGEMENT
# Deep sleep allows the keyboard to turn off completely after 15 mins
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_IDLE_TIMEOUT=60000

# BLUETOOTH
# Increase signal strength for better split connectivity
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y